pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
            dir('untitled'){
                sh 'chmod +x gradlew'
                sh './gradlew build'
                }
            }
        }

        stage('Test') {
            steps {
             dir('untitled'){
                sh './gradlew test'
                }
            }
        }
    }

    post {
        always {
            junit '**/build/test-results/test/*.xml'
        }
        success {
            echo 'Build and test succeeded!'
            sh 'echo "Build Success - $(date)" > build-result.txt'
            archiveArtifacts artifacts: 'build-result.txt'
              mail to: 'emilypark0721@gmail.com',
                     subject: "빌드 성공: ${env.JOB_NAME}",
                     body: "빌드가 성공했습니다!\n\n빌드 번호: ${env.BUILD_NUMBER}\n확인: ${env.BUILD_URL}"
            }
        }
        failure {
            echo 'Build or test failed!'
        }
    }
}